---
language: java

sudo: false

script:
  - mvn cobertura:cobertura -f ./uia.message/pom.xml --settings .travis.settings.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
  
branches:
  only:
  - 0.5.0.0